INSERT INTO categories (name, description) VALUES
    ('Pens', 'Various types of pens for writing.'),
    ('Pencils', 'Writing pencils and colored pencils.'),
    ('Notebooks', 'Notebooks of different sizes and styles.'),
    ('Erasers', 'Erasers for erasing pencils and pens.'),
    ('Markers', 'Highlighters and permanent markers.'),
    ('Planners', 'Planners for planning and organizing.'),
    ('Papers', 'Papers of different weights and textures.'),
    ('Staplers', 'Staplers for attaching sheets of paper.'),
    ('Scissors', 'Scissors for cutting paper and materials.'),
    ('Organizers', 'Organizers for office and stationery.');

INSERT INTO suppliers (name, cnpj) VALUES
    ('PaperMart', '12345678901234'),
    ('StationeryPlus', '98765432109876'),
    ('OfficeEssentials', '45678901234567');

INSERT INTO supplier_addresses (supplier_id, street, number, neighborhood, city, state, country, zip_code) VALUES
    (1, '123 Main St', '1', 'Downtown', 'Metropolis', 'CA', 'USA', '12345'),
    (1, '456 Elm St', '20', 'Uptown', 'Metropolis', 'CA', 'USA', '12345'),
    (2, '789 Oak St', '5', 'Midtown', 'Metroville', 'NY', 'USA', '54321'),
    (2, '101 Pine St', '15', 'Downtown', 'Metroville', 'NY', 'USA', '54321'),
    (3, '321 Cedar St', '10', 'Uptown', 'Megatown', 'TX', 'USA', '67890'),
    (3, '654 Maple St', '25', 'Downtown', 'Megatown', 'TX', 'USA', '67890');

INSERT INTO supplier_phones (supplier_id, number, type, responsible) VALUES
    (1, '+1234567890', 'Main', 'John Doe'),
    (1, '+1987654321', 'Secondary', 'Jane Smith'),
    (2, '+1555555555', 'Main', 'Alice Johnson'),
    (2, '+1777777777', 'Secondary', 'Bob Smith'),
    (3, '+1888888888', 'Main', 'Eve Brown'),
    (3, '+1999999999', 'Secondary', 'Chris Wilson');

INSERT INTO products (name, description, brand, model, price, category_id) VALUES
    ('Ballpoint Pen', 'Black ballpoint pen for everyday writing tasks.', 'Bic', 'Cristal', 1.99, 1),
    ('Gel Pen Set', 'Set of assorted gel pens in vibrant colors.', 'PaperMate', 'InkJoy Gel', 9.99, 1),
    ('Fountain Pen', 'Classic fountain pen with refillable ink cartridge.', 'Parker', 'Sonnet', 49.99, 1),
    ('Highlighter', 'Yellow highlighter marker for emphasizing text.', 'Sharpie', 'Accent', 1.49, 1),
    ('Rollerball Pen', 'Smooth writing rollerball pen with fine tip.', 'Uni-ball', 'Vision Elite', 2.99, 1),
    ('Mechanical Pencils', 'Pack of mechanical pencils with refillable lead.', 'Pentel', 'Sharp', 4.99, 2),
    ('Wooden Pencils', 'Classic wooden pencils with eraser tips.', 'Dixon', 'Ticonderoga', 3.49, 2),
    ('Colored Pencils', 'Set of vibrant colored pencils for artwork.', 'Prismacolor', 'Premier', 12.99, 2),
    ('HB Pencils', 'Standard HB pencils for writing and sketching.', 'Faber-Castell', 'Goldfaber', 2.99, 2),
    ('Mechanical Pencil Set', 'Set of mechanical pencils with assorted lead sizes.', 'Zebra', 'M-301', 7.99, 2),
    ('College Ruled Notebook', 'Classic college-ruled notebook with wire binding.', 'Mead', 'Five Star', 6.99, 3),
    ('Sketchbook', 'Hardcover sketchbook with acid-free paper.', 'Strathmore', '400 Series', 14.99, 3),
    ('Composition Notebook', 'Standard composition notebook with sewn binding.', 'Roaring Spring', 'Wide Ruled', 2.99, 3),
    ('Bullet Journal', 'Dotted bullet journal for creative planning.', 'Leuchtturm1917', 'A5 Hardcover', 19.99, 3),
    ('Planner', 'Weekly planner with monthly overviews and goal-setting pages.', 'Blue Sky', 'Passages', 9.99, 3),
    ('White Erasers', 'Soft white erasers for pencil marks.', 'PaperMate', 'Pink Pearl', 0.99, 4),
    ('Kneaded Eraser', 'Kneaded eraser for graphite and charcoal.', 'Prismacolor', 'ArtGum', 1.99, 4),
    ('Vinyl Erasers', 'Vinyl erasers for clean erasing.', 'Pentel', 'Hi-Polymer', 1.49, 4),
    ('Electric Eraser', 'Battery-powered eraser for precise corrections.', 'Sakura', 'Electric Eraser', 9.99, 4),
    ('Block Eraser', 'Large block eraser for heavy erasing.', 'Staedtler', 'Mars Plastic', 1.99, 4),
    ('Permanent Markers', 'Set of permanent markers for labeling.', 'Sharpie', 'Fine Point', 7.99, 5),
    ('Dry Erase Markers', 'Pack of dry erase markers for whiteboards.', 'Expo', 'Chisel Tip', 6.49, 5),
    ('Highlighter Set', 'Assorted highlighter set in various colors.', 'Zebra', 'Mildliner', 11.99, 5),
    ('Fabric Markers', 'Fabric markers for permanent textile designs.', 'Tulip', 'Dual-Tip', 8.99, 5),
    ('Brush Markers', 'Brush tip markers for calligraphy and artwork.', 'Tombow', 'Dual Brush', 24.99, 5),
    ('Daily Planner', 'Daily planner with hourly schedule and to-do lists.', 'Day Designer', 'The Original', 29.99, 6),
    ('Weekly Planner', 'Weekly planner with goal-setting pages and habit trackers.', 'Passion Planner', 'Classic', 24.99, 6),
    ('Monthly Planner', 'Monthly planner with spacious calendar pages.', 'Blue Sky', 'Day Designer', 14.99, 6),
    ('Undated Planner', 'Undated planner for flexible planning.', 'Panda Planner', 'Pro', 19.99, 6),
    ('Academic Planner', 'Academic planner with academic calendars and project planning sections.', 'Erin Condren', 'LifePlanner', 34.99, 6),
    ('Printer Paper', 'Standard printer paper for everyday printing.', 'Hammermill', 'Copy Plus', 5.99, 7),
    ('Cardstock', 'Heavyweight cardstock for crafting and card-making.', 'Neenah', 'Exact Index', 12.99, 7),
    ('Photo Paper', 'High-quality photo paper for vibrant photo prints.', 'Canon', 'Photo Paper Plus', 19.99, 7),
    ('Construction Paper', 'Assorted construction paper for art projects.', 'Crayola', 'Construction Paper', 7.49, 7),
    ('Watercolor Paper', 'Cold press watercolor paper for painting.', 'Arches', 'Watercolor Block', 24.99, 7),
    ('Desktop Stapler', 'Classic desktop stapler for stapling papers.', 'Swingline', '747', 14.99, 8),
    ('Electric Stapler', 'Electric stapler for effortless stapling.', 'Bostitch', 'Impulse 25', 39.99, 8),
    ('Heavy Duty Stapler', 'Heavy duty stapler for stapling thick documents.', 'Rapid', 'HD9', 39.99, 8),
    ('Plier Stapler', 'Plier stapler for stapling booklets and thick stacks of paper.', 'Bostitch', 'B8', 19.99, 8),
    ('Mini Stapler', 'Compact mini stapler for on-the-go stapling.', 'ACCO', 'Mini', 2.99, 8),
    ('Office Scissors', 'Standard office scissors for cutting paper.', 'Westcott', 'Titanium', 9.99, 9),
    ('Craft Scissors', 'Assorted craft scissors for decorative cutting.', 'Fiskars', 'Softgrip', 14.99, 9),
    ('Kids Scissors', 'Safety scissors for kids with blunt tips.', 'Scotch', 'Soft Touch', 2.99, 9),
    ('Kitchen Scissors', 'Multipurpose kitchen scissors for food preparation.', 'OXO', 'Good Grips', 17.99, 9),
    ('Sewing Scissors', 'Precision sewing scissors for fabric cutting.', 'Gingher', 'Knife Edge', 24.99, 9),
    ('Desk Organizer', 'Desktop organizer for pens, notes, and supplies.', 'Mind Reader', 'Mesh Desk Organizer', 12.99, 10),
    ('File Organizer', 'File organizer for sorting and storing documents.', 'SimpleHouseware', 'Mesh Desk File Organizer', 16.99, 10),
    ('Drawer Organizer', 'Drawer organizer for organizing small items.', 'STORi', 'Clear Plastic Drawer Organizers', 9.99, 10),
    ('Wall Organizer', 'Wall-mounted organizer for mail and keys.', 'Designstyles', 'Wall Hanging Mail Organizer', 19.99, 10),
    ('Drawer Cart', 'Rolling drawer cart for storage and organization.', 'Honey-Can-Do', '3-Drawer Rolling Cart', 29.99, 10);
